//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metalurgica.Px_GuiaDespacho {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="www.informat.cl", ConfigurationName="Px_GuiaDespacho.XMLDocVtaExtSoapPort")]
    public interface XMLDocVtaExtSoapPort {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (XMLDocVtaExt.Execute) del mensaje ExecuteRequest no coincide con el valor predeterminado (Execute)
        [System.ServiceModel.OperationContractAttribute(Action="www.informat.claction/AXMLDOCVTAEXT.Execute", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Metalurgica.Px_GuiaDespacho.ExecuteResponse Execute(Metalurgica.Px_GuiaDespacho.ExecuteRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.informat.cl/ws")]
    public partial class SDT_ERRORES_ERROR : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int nUMERRORField;
        
        private string dESCERRORField;
        
        /// <remarks/>
        public int NUMERROR {
            get {
                return this.nUMERRORField;
            }
            set {
                this.nUMERRORField = value;
                this.RaisePropertyChanged("NUMERROR");
            }
        }
        
        /// <remarks/>
        public string DESCERROR {
            get {
                return this.dESCERRORField;
            }
            set {
                this.dESCERRORField = value;
                this.RaisePropertyChanged("DESCERROR");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="XMLDocVtaExt.Execute", WrapperNamespace="www.informat.cl", IsWrapped=true)]
    public partial class ExecuteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.informat.cl", Order=0)]
        public string Xmlin;
        
        public ExecuteRequest() {
        }
        
        public ExecuteRequest(string Xmlin) {
            this.Xmlin = Xmlin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="XMLDocVtaExt.ExecuteResponse", WrapperNamespace="www.informat.cl", IsWrapped=true)]
    public partial class ExecuteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.informat.cl", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://www.informat.cl/ws", IsNullable=false)]
        public Metalurgica.Px_GuiaDespacho.SDT_ERRORES_ERROR[] Xmlout;
        
        public ExecuteResponse() {
        }
        
        public ExecuteResponse(Metalurgica.Px_GuiaDespacho.SDT_ERRORES_ERROR[] Xmlout) {
            this.Xmlout = Xmlout;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface XMLDocVtaExtSoapPortChannel : Metalurgica.Px_GuiaDespacho.XMLDocVtaExtSoapPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class XMLDocVtaExtSoapPortClient : System.ServiceModel.ClientBase<Metalurgica.Px_GuiaDespacho.XMLDocVtaExtSoapPort>, Metalurgica.Px_GuiaDespacho.XMLDocVtaExtSoapPort {
        
        public XMLDocVtaExtSoapPortClient() {
        }
        
        public XMLDocVtaExtSoapPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public XMLDocVtaExtSoapPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XMLDocVtaExtSoapPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XMLDocVtaExtSoapPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Metalurgica.Px_GuiaDespacho.ExecuteResponse Metalurgica.Px_GuiaDespacho.XMLDocVtaExtSoapPort.Execute(Metalurgica.Px_GuiaDespacho.ExecuteRequest request) {
            return base.Channel.Execute(request);
        }
        
        public Metalurgica.Px_GuiaDespacho.SDT_ERRORES_ERROR[] Execute(string Xmlin) {
            Metalurgica.Px_GuiaDespacho.ExecuteRequest inValue = new Metalurgica.Px_GuiaDespacho.ExecuteRequest();
            inValue.Xmlin = Xmlin;
            Metalurgica.Px_GuiaDespacho.ExecuteResponse retVal = ((Metalurgica.Px_GuiaDespacho.XMLDocVtaExtSoapPort)(this)).Execute(inValue);
            return retVal.Xmlout;
        }
    }
}
