//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metalurgica.WsCrud {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.Ssingest.cl/", ConfigurationName="WsCrud.CrudSoap")]
    public interface CrudSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Ssingest.cl/GuardarBodega", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Metalurgica.WsCrud.Bodega GuardarBodega(Metalurgica.WsCrud.Bodega bodega);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Ssingest.cl/DesactivarBodega", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Metalurgica.WsCrud.Bodega DesactivarBodega(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Ssingest.cl/ListarBodega", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Metalurgica.WsCrud.ListaDataSet ListarBodega();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Ssingest.cl/ObtenerBodega", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Metalurgica.WsCrud.Bodega ObtenerBodega(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Ssingest.cl/GuardarCamion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Metalurgica.WsCrud.Camion GuardarCamion(Metalurgica.WsCrud.Camion camion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Ssingest.cl/DesactivarCamion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Metalurgica.WsCrud.Camion DesactivarCamion(string patente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Ssingest.cl/ListarCamion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Metalurgica.WsCrud.ListaDataSet ListarCamion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Ssingest.cl/ObtenerCamion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Metalurgica.WsCrud.Camion ObtenerCamion(string patente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Ssingest.cl/GuardarMaquina", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Metalurgica.WsCrud.Maquina GuardarMaquina(Metalurgica.WsCrud.Maquina maquina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Ssingest.cl/DesactivarMaquina", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Metalurgica.WsCrud.Maquina DesactivarMaquina(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Ssingest.cl/ListarMaquina", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Metalurgica.WsCrud.ListaDataSet ListarMaquina();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Ssingest.cl/ObtenerMaquina", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Metalurgica.WsCrud.Maquina ObtenerMaquina(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Ssingest.cl/ListarAyudaSql", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Metalurgica.WsCrud.ListaDataSet ListarAyudaSql(string sql);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.Ssingest.cl/")]
    public partial class Bodega : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string tipoField;
        
        private string nombreField;
        
        private string descripcionField;
        
        private string activaField;
        
        private string mensajeErrorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("Tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("Descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Activa {
            get {
                return this.activaField;
            }
            set {
                this.activaField = value;
                this.RaisePropertyChanged("Activa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string MensajeError {
            get {
                return this.mensajeErrorField;
            }
            set {
                this.mensajeErrorField = value;
                this.RaisePropertyChanged("MensajeError");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.Ssingest.cl/")]
    public partial class Maquina : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nombreField;
        
        private string descripcionField;
        
        private string activaField;
        
        private string mensajeErrorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("Descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Activa {
            get {
                return this.activaField;
            }
            set {
                this.activaField = value;
                this.RaisePropertyChanged("Activa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string MensajeError {
            get {
                return this.mensajeErrorField;
            }
            set {
                this.mensajeErrorField = value;
                this.RaisePropertyChanged("MensajeError");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.Ssingest.cl/")]
    public partial class Camion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string patenteField;
        
        private string transportistaField;
        
        private string obsField;
        
        private string activoField;
        
        private string mensajeErrorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Patente {
            get {
                return this.patenteField;
            }
            set {
                this.patenteField = value;
                this.RaisePropertyChanged("Patente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Transportista {
            get {
                return this.transportistaField;
            }
            set {
                this.transportistaField = value;
                this.RaisePropertyChanged("Transportista");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Obs {
            get {
                return this.obsField;
            }
            set {
                this.obsField = value;
                this.RaisePropertyChanged("Obs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("Activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string MensajeError {
            get {
                return this.mensajeErrorField;
            }
            set {
                this.mensajeErrorField = value;
                this.RaisePropertyChanged("MensajeError");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.Ssingest.cl/")]
    public partial class ListaDataSet : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Data.DataSet _dataSetField;
        
        private string _errorField;
        
        private System.Data.DataSet dataSetField;
        
        private string mensajeErrorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Data.DataSet _dataSet {
            get {
                return this._dataSetField;
            }
            set {
                this._dataSetField = value;
                this.RaisePropertyChanged("_dataSet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string _error {
            get {
                return this._errorField;
            }
            set {
                this._errorField = value;
                this.RaisePropertyChanged("_error");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.Data.DataSet DataSet {
            get {
                return this.dataSetField;
            }
            set {
                this.dataSetField = value;
                this.RaisePropertyChanged("DataSet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MensajeError {
            get {
                return this.mensajeErrorField;
            }
            set {
                this.mensajeErrorField = value;
                this.RaisePropertyChanged("MensajeError");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CrudSoapChannel : Metalurgica.WsCrud.CrudSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CrudSoapClient : System.ServiceModel.ClientBase<Metalurgica.WsCrud.CrudSoap>, Metalurgica.WsCrud.CrudSoap {
        
        public CrudSoapClient() {
        }
        
        public CrudSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CrudSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CrudSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CrudSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Metalurgica.WsCrud.Bodega GuardarBodega(Metalurgica.WsCrud.Bodega bodega) {
            return base.Channel.GuardarBodega(bodega);
        }
        
        public Metalurgica.WsCrud.Bodega DesactivarBodega(int id) {
            return base.Channel.DesactivarBodega(id);
        }
        
        public Metalurgica.WsCrud.ListaDataSet ListarBodega() {
            return base.Channel.ListarBodega();
        }
        
        public Metalurgica.WsCrud.Bodega ObtenerBodega(int id) {
            return base.Channel.ObtenerBodega(id);
        }
        
        public Metalurgica.WsCrud.Camion GuardarCamion(Metalurgica.WsCrud.Camion camion) {
            return base.Channel.GuardarCamion(camion);
        }
        
        public Metalurgica.WsCrud.Camion DesactivarCamion(string patente) {
            return base.Channel.DesactivarCamion(patente);
        }
        
        public Metalurgica.WsCrud.ListaDataSet ListarCamion() {
            return base.Channel.ListarCamion();
        }
        
        public Metalurgica.WsCrud.Camion ObtenerCamion(string patente) {
            return base.Channel.ObtenerCamion(patente);
        }
        
        public Metalurgica.WsCrud.Maquina GuardarMaquina(Metalurgica.WsCrud.Maquina maquina) {
            return base.Channel.GuardarMaquina(maquina);
        }
        
        public Metalurgica.WsCrud.Maquina DesactivarMaquina(int id) {
            return base.Channel.DesactivarMaquina(id);
        }
        
        public Metalurgica.WsCrud.ListaDataSet ListarMaquina() {
            return base.Channel.ListarMaquina();
        }
        
        public Metalurgica.WsCrud.Maquina ObtenerMaquina(int id) {
            return base.Channel.ObtenerMaquina(id);
        }
        
        public Metalurgica.WsCrud.ListaDataSet ListarAyudaSql(string sql) {
            return base.Channel.ListarAyudaSql(sql);
        }
    }
}
