//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metalurgica.Px_MovExistenciasINET {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="www.informat.cl", ConfigurationName="Px_MovExistenciasINET.wsmovexiallSoapPort")]
    public interface wsmovexiallSoapPort {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (wsmovexiall.Execute) del mensaje ExecuteRequest no coincide con el valor predeterminado (Execute)
        [System.ServiceModel.OperationContractAttribute(Action="www.informat.claction/AWSMOVEXIALL.Execute", ReplyAction="*")]
        Metalurgica.Px_MovExistenciasINET.ExecuteResponse Execute(Metalurgica.Px_MovExistenciasINET.ExecuteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="wsmovexiall.Execute", WrapperNamespace="www.informat.cl", IsWrapped=true)]
    public partial class ExecuteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.informat.cl", Order=0)]
        public string Intrasnporte;
        
        public ExecuteRequest() {
        }
        
        public ExecuteRequest(string Intrasnporte) {
            this.Intrasnporte = Intrasnporte;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="wsmovexiall.ExecuteResponse", WrapperNamespace="www.informat.cl", IsWrapped=true)]
    public partial class ExecuteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.informat.cl", Order=0)]
        public string Outtansporte;
        
        public ExecuteResponse() {
        }
        
        public ExecuteResponse(string Outtansporte) {
            this.Outtansporte = Outtansporte;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsmovexiallSoapPortChannel : Metalurgica.Px_MovExistenciasINET.wsmovexiallSoapPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsmovexiallSoapPortClient : System.ServiceModel.ClientBase<Metalurgica.Px_MovExistenciasINET.wsmovexiallSoapPort>, Metalurgica.Px_MovExistenciasINET.wsmovexiallSoapPort {
        
        public wsmovexiallSoapPortClient() {
        }
        
        public wsmovexiallSoapPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsmovexiallSoapPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsmovexiallSoapPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsmovexiallSoapPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Metalurgica.Px_MovExistenciasINET.ExecuteResponse Metalurgica.Px_MovExistenciasINET.wsmovexiallSoapPort.Execute(Metalurgica.Px_MovExistenciasINET.ExecuteRequest request) {
            return base.Channel.Execute(request);
        }
        
        public string Execute(string Intrasnporte) {
            Metalurgica.Px_MovExistenciasINET.ExecuteRequest inValue = new Metalurgica.Px_MovExistenciasINET.ExecuteRequest();
            inValue.Intrasnporte = Intrasnporte;
            Metalurgica.Px_MovExistenciasINET.ExecuteResponse retVal = ((Metalurgica.Px_MovExistenciasINET.wsmovexiallSoapPort)(this)).Execute(inValue);
            return retVal.Outtansporte;
        }
    }
}
