//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metalurgica.WsSesion {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsSesion.WS_SesionSoap")]
    public interface WS_SesionSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iniciar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Metalurgica.WsSesion.Sesion Iniciar(string Usuario, int Maquina, string Terminal, string App);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Terminar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Metalurgica.WsSesion.Sesion Terminar(int idSession);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FechaHora", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Metalurgica.WsSesion.Sesion FechaHora();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Metalurgica.WsSesion.ListaDataSet ObtenerUsuario(string login, string clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerDatosUsuarioLogeado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Metalurgica.WsSesion.ListaDataSet ObtenerDatosUsuarioLogeado(string iUser, string iNroMaquina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistraLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string RegistraLogin(string iUser, string iNroMaquina, string iPc_Accede);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Sesion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private System.DateTime fechaField;
        
        private string mensajeErrorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("Fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MensajeError {
            get {
                return this.mensajeErrorField;
            }
            set {
                this.mensajeErrorField = value;
                this.RaisePropertyChanged("MensajeError");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ListaDataSet : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Data.DataSet _dataSetField;
        
        private string _errorField;
        
        private System.Data.DataSet dataSetField;
        
        private string mensajeErrorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Data.DataSet _dataSet {
            get {
                return this._dataSetField;
            }
            set {
                this._dataSetField = value;
                this.RaisePropertyChanged("_dataSet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string _error {
            get {
                return this._errorField;
            }
            set {
                this._errorField = value;
                this.RaisePropertyChanged("_error");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.Data.DataSet DataSet {
            get {
                return this.dataSetField;
            }
            set {
                this.dataSetField = value;
                this.RaisePropertyChanged("DataSet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MensajeError {
            get {
                return this.mensajeErrorField;
            }
            set {
                this.mensajeErrorField = value;
                this.RaisePropertyChanged("MensajeError");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WS_SesionSoapChannel : Metalurgica.WsSesion.WS_SesionSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_SesionSoapClient : System.ServiceModel.ClientBase<Metalurgica.WsSesion.WS_SesionSoap>, Metalurgica.WsSesion.WS_SesionSoap {
        
        public WS_SesionSoapClient() {
        }
        
        public WS_SesionSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WS_SesionSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_SesionSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_SesionSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Metalurgica.WsSesion.Sesion Iniciar(string Usuario, int Maquina, string Terminal, string App) {
            return base.Channel.Iniciar(Usuario, Maquina, Terminal, App);
        }
        
        public Metalurgica.WsSesion.Sesion Terminar(int idSession) {
            return base.Channel.Terminar(idSession);
        }
        
        public Metalurgica.WsSesion.Sesion FechaHora() {
            return base.Channel.FechaHora();
        }
        
        public Metalurgica.WsSesion.ListaDataSet ObtenerUsuario(string login, string clave) {
            return base.Channel.ObtenerUsuario(login, clave);
        }
        
        public Metalurgica.WsSesion.ListaDataSet ObtenerDatosUsuarioLogeado(string iUser, string iNroMaquina) {
            return base.Channel.ObtenerDatosUsuarioLogeado(iUser, iNroMaquina);
        }
        
        public string RegistraLogin(string iUser, string iNroMaquina, string iPc_Accede) {
            return base.Channel.RegistraLogin(iUser, iNroMaquina, iPc_Accede);
        }
    }
}
